import Foundation

/// Source of truth for the body-emission contract documented in EMISSION.md.
/// `renderMarkdown()` is the doc; `EmissionContractTests` asserts the committed
/// `Resources/PublishStarter/EMISSION.md` matches, so the doc cannot drift.
///
/// The positive-space examples are GENERATED by calling the real
/// `LaTeXBodyEmitter` against a single-piece `ProjectAST` — they cannot lie
/// about what the emitter produces. The negative-space, locality-criterion,
/// style-file, and recovery sections are prose contracts maintained here.
public enum EmissionContract {

    /// One positive-space example: a source snippet whose LaTeX output is
    /// produced by running the real emitter (never hand-transcribed).
    public struct Example {
        public let label: String
        public let source: String
        public init(label: String, source: String) {
            self.label = label
            self.source = source
        }
    }

    public static let proseExamples: [Example] = [
        .init(label: "Paragraph", source: "A plain sentence."),
        .init(label: "Heading level 1", source: "# Chapter Title"),
        .init(label: "Blockquote with emphasis", source: "> A quote with *italic* inside."),
        .init(label: "Scene break", source: "***"),
        .init(label: "Inline mix", source: "Text with *em*, **strong**, _under_, `code`."),
        .init(label: "Anchor-only paragraph", source: "<!-- ¶ab12 -->"),
        .init(label: "Bold italic", source: "Both ***kinds*** now."),
        .init(label: "Strikethrough", source: "Cut ~~this clause~~ entirely."),
        .init(label: "Escaped asterisk", source: #"A literal \*star\* here."#),
        .init(label: "Underscore is literal in prose", source: "snake_case stays flat."),
        .init(label: "List", source: "- one\n- two"),
        .init(label: "Fenced code block (mangle guard, not code support)",
              source: "```\n*not em*\n`nor code`\n```"),
    ]

    public static let fountainExamples: [Example] = [
        // The trailing `#4A#` is extracted into a scene number (Task 11) and
        // renders right-aligned via `\scenenumber{4A}`; the heading text loses
        // the bracket.
        .init(label: "Scene heading with number",
              source: "INT. HOUSE - DAY #4A#"),
        .init(label: "Dual dialogue", source: "ALICE\nHello.\n\nBOB ^\nHi."),
        .init(label: "Lyric", source: "~The moon is out"),
        .init(label: "Centered", source: "> THE END <"),
        .init(label: "Page break (===)", source: "==="),
        .init(label: "Boneyard omitted", source: "/* gone */\n\nKept."),
        .init(label: "Note omitted", source: "Before [[skip me]] after."),
        .init(label: "Title page (F6: emits via \\screenplaytitleblock)",
              source: "Title: The Play\nAuthor: A. Writer\n\nINT. HOUSE - DAY\n\nAction."),
    ]

    /// Render the `body.tex` the emitter actually produces for a prose snippet.
    /// Builds a single-piece AST and calls the real config-threaded emitter.
    static func emittedProse(_ source: String) -> String {
        let ast = ProjectASTBuilder.build(from: SinglePieceSource(
            pieceID: "ex01", title: "Example", mode: .prose, text: source))
        return LaTeXBodyEmitter.emit(ast, config: PublishConfig())
    }

    /// Render the `body.tex` the emitter actually produces for a fountain
    /// snippet. Mirrors `emittedProse` with `mode: .fountain`.
    static func emittedFountain(_ source: String) -> String {
        let ast = ProjectASTBuilder.build(from: SinglePieceSource(
            pieceID: "ex01", title: "Example", mode: .fountain, text: source))
        return LaTeXBodyEmitter.emit(ast, config: PublishConfig())
    }

    /// F5: the copy actually written into a project's `.maugham/publish/`
    /// directory. Adds a stamped, app-owned header — invisible in rendered
    /// Markdown (an HTML comment), so the doc reads identically — ahead of
    /// the byte-unchanged `renderMarkdown()`. The stamp makes staleness
    /// self-evident: a project inited under an old app version and never
    /// recompiled since carries that version in its header, not the
    /// installed app's.
    public static func renderProjectCopy(appVersion: String) -> String {
        "<!-- Generated by Maugham \(appVersion) — app-owned; refreshed on every compile/preview. Do not edit. -->\n\n"
            + renderMarkdown()
    }

    public static func renderMarkdown() -> String {
        var out = "# EMISSION.md — Body Emission Contract\n\n"
        out += "_Generated from `EmissionContract.swift`. Do not hand-edit; "
        out += "edit the Swift source and regenerate (the test enforces the match)._\n\n"
        out += "This is the authoritative description of what the LaTeX body emitter "
        out += "produces for each source pattern. The positive-space examples below are "
        out += "rendered by calling the real emitter, so they always reflect reality.\n\n"
        out += localityCriterion + "\n\n"
        out += "## Positive space — recognized patterns\n\n"
        for ex in proseExamples {
            out += "### \(ex.label)\n\n```\n\(ex.source)\n```\n\nemits:\n\n```latex\n\(emittedProse(ex.source))\n```\n\n"
        }
        out += "## Fountain positive space — recognized patterns\n\n"
        for ex in fountainExamples {
            out += "### \(ex.label)\n\n```\n\(ex.source)\n```\n\nemits:\n\n```latex\n\(emittedFountain(ex.source))\n```\n\n"
        }
        out += negativeSpace + "\n\n"
        out += styleFileContract + "\n\n"
        out += fontsConvention + "\n\n"
        out += languageEditionContract + "\n\n"
        out += recoveryNote + "\n\n"
        out += epubIterationNote + "\n"
        return out
    }

    static let localityCriterion = """
    ## Where does a typographic move live? The locality criterion

    > Does honoring this override require **global** knowledge the piece cannot \
    have on its own? **Global → config. Local → template (per-piece `.tex`).**

    | Override | Lives in | Why |
    | --- | --- | --- |
    | `start_on` (recto/verso) | config | needs global page state |
    | `include_in_toc` | config | needs global ToC state |
    | `title_override` | config | a declaration, not typography |
    | Numbering visibility | template (per-piece `.tex`) | local to the piece |
    | Final-line isolation | template (per-piece `.tex`) | local to the piece |
    | Drop caps | template (per-piece `.tex`) | local to the piece |
    | Ornaments | template (per-piece `.tex`) | local to the piece |
    """

    static let negativeSpace = """
    ## Negative space — patterns the emitter does NOT give special meaning

    Anything not listed under "positive space" passes through as its constituent \
    text/inline nodes. Specifically, and from real use:

    - A line beginning with `:` (e.g. `: foo`) → literal paragraph text. No \
    definition-list semantics.
    - `:*emphasis*` → a literal colon then `\\emph{emphasis}`. No marker semantics.
    - `**Context: 0%**` → `\\textbf{Context: 0\\%}`. There is no progress-meter \
    or status rendering — it is ordinary bold text.
    - Catch-all: any other punctuation, sigil, or convention not documented under \
    "positive space" carries no special meaning and renders as its literal text.

    If you need any of these to render specially, that's a per-piece `.tex` hook.
    """

    static let styleFileContract = """
    ## Per-piece style files (`style_file`)

    Set via `set_piece_style`. Sourced inside a TeX group, **before** the piece's \
    environment opens:

    ```latex
    \\begingroup
      \\input{pieces/<file>}      % runs here, at source time
      \\begin{prose}{Title} ... \\end{prose}
    \\endgroup
    ```

    A per-piece file **MAY**: `\\renewcommand`, `\\newcommand`, `\\definecolor`, \
    `\\renewenvironment`, and emit arbitrary body LaTeX at file top (e.g. a per-piece \
    **title page** — put it before any `\\renewcommand`).

    A per-piece file **MAY NOT**: `\\usepackage` (packages load only in the \
    preamble) or change `\\geometry` (page geometry is preamble-level and does \
    not revert at `\\endgroup`). These are collection-level — edit `preamble.tex`.

    **Scoping, verified by compile probe** (bundled tectonic 0.15.0, LaTeX \
    kernel 2021-11-15; pinned by `StarterTemplateDefectProbeTests`): command \
    renewals made at style-file scope — `\\renewcommand`, \
    `\\RenewDocumentCommand`, `\\DeclareRobustCommand`, including renewals of \
    robust kernel commands like `\\textbf` — revert at the `\\endgroup` and \
    cannot restyle later pieces. What DOES escape the group: `\\global`-prefixed \
    definitions (never use them in a style file) and counter changes \
    (`\\setcounter`/`\\addtocounter` — LaTeX counters are global).

    **xparse declarations are global, unlike renewals.** `\\NewDocumentCommand`, \
    `\\NewDocumentEnvironment`, and the wider xparse `\\Declare…`/`\\New…` family are \
    *new-name* declarations, not renewals of an existing command — they take effect \
    globally and **cross piece boundaries**, even when declared inside a style \
    file's `\\begingroup`/`\\endgroup`. This is a different animal from the \
    *renewal* scoping documented above (`\\renewcommand`, `\\RenewDocumentCommand`, \
    `\\DeclareRobustCommand` of an already-existing name correctly revert at \
    `\\endgroup`). Introducing a brand-new command from a per-piece style file \
    risks a name collision that clobbers or shadows a later piece; declare shared \
    vocabulary in `preamble.tex` instead, where its global lifetime is expected.

    **Active-catcode tricks destabilize hyperref (field-verified).** Avoid \
    `\\catcode`-based active-character tricks in style files (e.g. making a \
    character active via `\\catcode\\`X=\\active`). hyperref's bookmark/anchor \
    machinery re-scans the token stream across multiple passes, and active \
    catcodes introduced mid-document destabilize that machinery in ways that are \
    hard to predict or debug. Use source-level constructs — an ordinary macro \
    invoked where you need the effect — instead of catcode reassignment.

    **Required pattern for restyling a heading or a kernel command.** Do NOT \
    renew a kernel command (`\\textbf`, `\\emph`, `\\scene`, …) at style-file \
    top level to restyle a piece's headings. Put the renewal **inside the \
    `\\pieceheading` hook** (or the piece environment's own body) so it is \
    scoped to where it fires — e.g. `\\renewcommand{\\pieceheading}[1]{{\\bfseries\\Large #1}\\addcontentsline{toc}{section}{#1}}`. \
    This is a **MUST**, not a preference, and it is what the Playlist templates \
    use. Reason: a real six-piece field compile once had a piece-2 style file \
    renew `\\textbf` to a `\\marginpar{...}` at style-file top level and the \
    restyle bled into a piece **two sections later** (a fountain title block and \
    its scene headings), even though a solo compile was correct and \
    `begingroup`/`endgroup` counts in `body.tex` balanced. The isolated \
    compile-probe reproduction of that exact shape does **not** leak under the \
    bundled tectonic (the renewal reverts at `\\endgroup` as documented above), \
    so the field mechanism is **unexplained** — the leading unproven suspect is \
    fontspec's lazy bold/em family setup interacting with the deferred \
    `\\marginpar` output routine. Because the field failure was real and its \
    trigger is not understood, the hook-scoped pattern is mandatory: it is \
    immune to the failure regardless of the mechanism, so top-level kernel-\
    command renewals in style files are unsupported and may restyle unrelated \
    pieces.

    **`\\screenplaytitleblock` (F6).** The fountain title block emits via \
    `\\screenplaytitleblock{body}` (one argument: all title-page fields in \
    declared order), `\\providecommand`-declared per fountain section \
    alongside `\\lyricline`/`\\centeredline`/`\\scenenumber` (default \
    reproduces the classic centered title-page layout byte-for-byte). It is \
    a sanctioned restyle hook, same class as `\\pieceheading` above — a \
    dedicated per-purpose command, not a shared kernel one — so restyle it \
    directly rather than reaching into kernel commands to fake the effect.
    """

    static let fontsConvention = """
    ## Fonts

    Custom body fonts compile deterministically under the bundled tectonic \
    (XeTeX engine + fontspec package).

    **To use a custom font:**

    1. Drop the `.otf` or `.ttf` file into `.maugham/publish/fonts/` via \
    `write_publish_file` (base64-encode the bytes; the tool writes it at the \
    path you specify under `build/` — place it as `build/fonts/<filename>`).
    2. Enable it in `preamble.tex` (collection-level; this is an aesthetic global, \
    not a per-piece override — per the locality criterion, fonts belong in the \
    preamble, never in config):
       ```latex
       \\usepackage{fontspec}
       \\setmainfont[Path=fonts/]{YourFont-Regular.otf}
       ```
    3. **Remove or comment out `\\usepackage[utf8]{inputenc}`** on the line above. \
    `inputenc` is incompatible with `fontspec` under XeTeX — leaving both active \
    will cause a compilation error.

    The starter `preamble.tex` ships with a commented-out fontspec block that \
    includes this reminder. Uncomment it and set your filename; the `inputenc` \
    removal is the only other required change.
    """

    static let languageEditionContract = """
    ## Language editions — template variants (F4)

    The resolver auto-picks `template.<lang>.tex` and per-piece \
    `<piece>.<lang>.tex` when compiling with a `language`, falling back to the \
    base file when a variant is absent. That resolution covers **only** those \
    two file kinds — it does not follow `\\input` lines inside them to \
    auto-resolve arbitrary partials. This is deliberate: a project may `\\input` \
    shared macros that must **not** vary by language, and auto-resolving every \
    `\\input` would silently make them vary.

    If your template inputs partials (`preamble.tex`, `frontmatter.tex`, \
    `backmatter.tex`, or similar), the language edition needs its own \
    `template.<lang>.tex` whose `\\input` lines point at language variants of \
    those partials; the resolver picks the template variant, and everything \
    else follows from it. A `frontmatter.<lang>.tex` sitting next to the base \
    file does nothing on its own — nothing errors, the base file just keeps \
    rendering — until a `template.<lang>.tex` `\\input`s it.
    """

    static let recoveryNote = """
    ## Recovery

    Overwriting or clearing a style file moves the prior version to Maugham's \
    trash (`.maugham/trash/`, 30-day sweep, undo via ⌘⌥Z). There is **no git** in \
    this workflow; the trash is the recovery path. `build/body.tex`, \
    `build/body.xhtml`, and `build/compile.log` are readable via `read_publish_file` \
    for diagnosing what the emitter and compiler produced.
    """

    static let epubIterationNote = """
    ## EPUB iteration — open-loop workflow

    PDF output is **CLOSED-LOOP**: Claude edits `template.tex` or `preamble.tex`, \
    runs a compile, and reads the result via `read_publication_page` — the rendered \
    page image is returned directly. Claude can see what changed.

    EPUB output is **OPEN-LOOP**: after each compile, `build/body.xhtml` contains \
    the assembled structural XHTML (one `<section>` block per piece, readable via \
    `read_publish_file build/body.xhtml`). However, this is NOT how a reading \
    application will render the file — final appearance depends on the reader's CSS \
    interpretation, its handling of embedded fonts, device defaults, and \
    night-mode overrides. Claude cannot observe those rendering decisions.

    EPUB iteration therefore works as follows:

    1. Claude proposes a CSS change in `styles.css` (via `write_publish_file`) and \
    compiles.
    2. Denver loads the new `.epub` in his reading application of choice (e.g. \
    Books, Calibre, Kindle).
    3. Denver describes what he sees — spacing, font size, chapter breaks, etc.
    4. Claude iterates based on Denver's description.

    This is the accepted workflow for personal-use EPUB. Closing the loop \
    (embedding a headless reader, capturing screenshots) is out of scope here.
    """
}

/// Minimal single-piece AST source for generating contract examples.
struct SinglePieceSource: ProjectASTBuilder.Source {
    let pieceID: String
    let title: String
    let mode: ProjectAST.Mode
    let text: String
    func orderedPieces() -> [ProjectASTBuilder.PieceRef] {
        [.init(pieceID: pieceID, title: title, mode: mode, displayText: text)]
    }
}
