import XCTest
import MaughamCore
@testable import Maugham

final class SlugifierTests: XCTestCase {

    func test_simpleTitle_lowercased_and_dashed() {
        XCTAssertEqual(Slugifier.slug(from: "Chapter 1"), "chapter-1")
    }

    func test_punctuation_isStripped() {
        XCTAssertEqual(Slugifier.slug(from: "The Razor's Edge!"), "the-razors-edge")
    }

    func test_consecutiveSpaces_collapseToSingleDash() {
        XCTAssertEqual(Slugifier.slug(from: "Chapter   One"), "chapter-one")
    }

    func test_leadingTrailingSpaces_areTrimmed() {
        XCTAssertEqual(Slugifier.slug(from: "  Hello World  "), "hello-world")
    }

    func test_emptyString_fallsBackToUntitled() {
        XCTAssertEqual(Slugifier.slug(from: ""), "untitled")
    }

    func test_onlyPunctuation_fallsBackToUntitled() {
        XCTAssertEqual(Slugifier.slug(from: "!!!???"), "untitled")
    }

    func test_unicode_isStrippedToAscii() {
        // "Über das Leben" — the umlaut decomposes via diacriticInsensitive folding
        XCTAssertEqual(Slugifier.slug(from: "Über das Leben"), "uber-das-leben")
    }

    func test_longTitle_truncatesTo40Chars() {
        let long = String(repeating: "a", count: 100)
        let slug = Slugifier.slug(from: long)
        XCTAssertEqual(slug.count, 40)
        XCTAssertEqual(slug, String(repeating: "a", count: 40))
    }

    func test_truncationDoesNotEndOnDash() {
        // 50 chars: 40 a's + dash + ... should truncate to 40 a's, not 39 a's + dash
        let title = String(repeating: "a", count: 40) + " " + String(repeating: "b", count: 10)
        let slug = Slugifier.slug(from: title)
        XCTAssertFalse(slug.hasSuffix("-"))
    }

    // MARK: - Parity tests: cases where researchSlugify and Slugifier.slug used to differ

    // Difference 1: diacritic/accent handling.
    // researchSlugify kept non-ASCII letters verbatim ("über" → "über").
    // Slugifier folds them to ASCII ("über" → "uber"). We standardise on Slugifier.
    func test_parity_accentedChars_foldedToASCII() {
        XCTAssertEqual(Slugifier.slug(from: "über"), "uber")
        XCTAssertEqual(Slugifier.slug(from: "naïve"), "naive")
        XCTAssertEqual(Slugifier.slug(from: "café"), "cafe")
        XCTAssertEqual(Slugifier.slug(from: "résumé"), "resume")
    }

    // Difference 2: underscore handling.
    // researchSlugify treated underscores as word-separators → dashes ("hello_world" → "hello-world").
    // Slugifier drops underscores entirely ("hello_world" → "helloworld"). We standardise on Slugifier.
    // Note: research filenames containing underscores (e.g. from prior slug+_assets/ folders) are NOT
    // generated by researchSlugify directly — that suffix is appended after slugification — so no
    // existing slug-derived filename produced an underscore via researchSlugify itself.
    func test_parity_underscore_isDropped() {
        XCTAssertEqual(Slugifier.slug(from: "hello_world"), "helloworld")
        XCTAssertEqual(Slugifier.slug(from: "foo_bar_baz"), "foobarbaz")
    }

    // Difference 3: max length.
    // researchSlugify had NO length cap; Slugifier caps at 40 chars. We standardise on Slugifier.
    func test_parity_veryLongTitle_truncatedTo40() {
        let title = String(repeating: "a", count: 200)
        let slug = Slugifier.slug(from: title)
        XCTAssertEqual(slug.count, 40)
        XCTAssertFalse(slug.hasSuffix("-"))
    }

    // Difference 4: empty/all-punctuation fallback.
    // Both functions returned "untitled" — same behavior, confirmed here.
    func test_parity_allPunctuation_fallsBackToUntitled() {
        XCTAssertEqual(Slugifier.slug(from: "!!!---___"), "untitled")
        XCTAssertEqual(Slugifier.slug(from: "..."), "untitled")
    }

    // Shared behavior: multiple spaces → single dash (same in both).
    func test_parity_multipleSpaces_collapsedToSingleDash() {
        XCTAssertEqual(Slugifier.slug(from: "hello   world"), "hello-world")
    }

    // Shared behavior: leading/trailing punctuation stripped, no trailing dash.
    func test_parity_leadingTrailingPunctuation_noTrailingDash() {
        XCTAssertEqual(Slugifier.slug(from: "  hello world  "), "hello-world")
        XCTAssertFalse(Slugifier.slug(from: "hello world ").hasSuffix("-"))
    }
}
